# Generated by Django 4.1.5 on 2023-02-08 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_images_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_reel',
            field=models.BooleanField(default=False),
        ),
    ]
